n, k = map(int, input().split())
x, y = map(int, input().split())
x, y = map(int, input().split())
print(x * y + (x * y + y % y))
print(x + y + y)
print(''.join(map(str, x)))
print(''.join(map(str, x)))
