t = int(input())
for _ in range(t):
    n, m = map(int, input().split())
    a = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().split()))
    s = list(map(int, input().()))