def main():
    n, m = map(int, input().split())
    a = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    y = list(map(int, input().split()))
    for i in range(n):