x = int(input())
x = int(input())
x = int(input())
x = int(input())
m = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
x = int(input())
if x == 0:
    print(-1)
elif :