n = int(input())
a = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
b = [int(x) for x in input().split()]
a.()