n = int(input())
a = list(map(int, input().split()))
a.sort()
b.sort()
a.sort()
b.sort()
a.sort()
b.sort()
a.sort()
b.sort()
a.sort()
b.sort()
a.sort()
b.sort()
print(a[0][0]- a[0][0]- a[0][0]- a[0][0]- a[0][0]- a[0][0]- a[0][0]- a[0][0]- a[0][0])