t = int(input())
for i in range(t):
	n = int(input())
	a = list(map(int, input().split()))
	s = a.index(n)
	b = a.count(n)
	b = a.count(n)
	b = arr.count(n)
	b = arr.count(n)
	b = a.count(n)
	b = a.count(n)
	b = arr.count(n)
	print(s * n)
